### ISSUE TITLE
Conflicting port number in the docker compose file

### ISSUE THREAD

**Issue by bap2pecs** [0xPolygon/supernets2-node#15]
in https://github.com/0xPolygon/supernets2-node/blob/main/docker-compose.yml,

there are both:

```
  supernets2-permissionless-node:
    container_name: supernets2-permissionless-node
    image: supernets2-node
    ports:
      - 8125:8125
```

and 

```
  supernets2-permissionless-node-forced-DAC:
    container_name: supernets2-permissionless-node-forced-DAC
    image: supernets2-node
    ports:
      - 8125:8125
```

it seems that one of them is the duplicate of the other.

I also noticed that the only difference of the two containers is this line:

```
      - SUPERNETS2_NODE_SYNCHRONIZER_TRUSTEDSEQUENCERURL=http://you-cant-touch-this:8123
```

what is this for?
